from django.contrib import admin
#from .models import AREA, CARGO, PERFIL_COMPETENCIAS, SUB_GERENCIA, GERENCIA, PERFIL, CUENTAS, EVALUACIONES, CUENTA_EVALUACION, COMPETENCIA_ASOCIADA, PLANES_DE_ACCION, ACCIONES_CLAVE

# Register your models here.

