# Generated by Django 3.2.7 on 2021-10-03 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreArea', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreCargo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rut', models.CharField(max_length=12, unique=True)),
                ('Nombre', models.CharField(max_length=50)),
                ('Contraseña', models.CharField(max_length=50)),
                ('Rol', models.CharField(max_length=50)),
                ('Correo', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadoEliminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdEmpleado', models.IntegerField()),
                ('Rut', models.CharField(max_length=12)),
                ('Nombre', models.CharField(max_length=50)),
                ('Contraseña', models.CharField(max_length=50)),
                ('Rol', models.CharField(max_length=50)),
                ('Correo', models.CharField(max_length=50)),
                ('FechaEliminacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreGerencia', models.CharField(max_length=50)),
                ('IdArea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='senttevaluationapp.area')),
            ],
        ),
        migrations.CreateModel(
            name='PlanAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accion', models.CharField(max_length=50)),
                ('Medicion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubGerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreSubgerencia', models.CharField(max_length=50)),
                ('IdGerencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='senttevaluationapp.gerencia')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rol', models.CharField(max_length=200)),
                ('RelacionEvaluado', models.CharField(max_length=50)),
                ('NombreEvaluador', models.CharField(max_length=50)),
                ('NombreCalibrador', models.CharField(max_length=50)),
                ('IdEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='senttevaluationapp.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombrePerfil', models.CharField(max_length=50)),
                ('IdCargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='senttevaluationapp.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.CharField(max_length=50)),
                ('Fase', models.CharField(max_length=50)),
                ('ComentarioCalibrador', models.CharField(max_length=50)),
                ('IdEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='senttevaluationapp.empleado')),
                ('IdPerfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='senttevaluationapp.perfil')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='IdSubGerencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='senttevaluationapp.subgerencia'),
        ),
        migrations.CreateModel(
            name='DetalleEv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaEvaluacion', models.DateField()),
                ('ComentarioEvaluador', models.CharField(max_length=100)),
                ('Calificacion', models.IntegerField()),
                ('AutoEvaluacion', models.IntegerField()),
                ('IdEvaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='senttevaluationapp.evaluacion')),
                ('IdPlanAccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='senttevaluationapp.planaccion')),
            ],
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreCompetencia', models.CharField(max_length=50)),
                ('Definicion', models.CharField(max_length=1000)),
                ('IdPerfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='senttevaluationapp.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='AccionClave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=1000)),
                ('IdCompetencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='senttevaluationapp.competencia')),
            ],
        ),
    ]
