# Generated by Django 3.2.6 on 2021-09-16 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AREA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CARGOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='COMPETENCIA_ASOCIADA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE', models.CharField(max_length=50)),
                ('DEFINICION', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EVALUACIONES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ESTADO', models.CharField(max_length=1)),
                ('COMPETENCIAS', models.CharField(max_length=40)),
                ('CALIFICACION', models.IntegerField()),
                ('COMENTARIOS', models.CharField(max_length=100)),
                ('TIPO_COMPETENCIA', models.CharField(max_length=30)),
                ('ACCION', models.CharField(max_length=30)),
                ('MEDICION', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GERENCIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PERFIL_COMPETENCIAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SUB_GERENCIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PLANES_DE_ACCION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ACCION', models.CharField(max_length=200)),
                ('MEDICION', models.CharField(max_length=200)),
                ('ID_COMPETENCIA_ASOCIADA', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='senttevaluationapp.competencia_asociada')),
                ('ID_EVALUACIONES', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='senttevaluationapp.evaluaciones')),
            ],
        ),
        migrations.CreateModel(
            name='PERFIL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE', models.CharField(max_length=50)),
                ('CORREO', models.CharField(max_length=50)),
                ('FECHA_ANTIGUEDAD', models.DateField()),
                ('ID_AREA', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='senttevaluationapp.area')),
                ('ID_CARGO', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='senttevaluationapp.cargos')),
                ('ID_GERENCIA', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='senttevaluationapp.gerencia')),
                ('ID_PERFIL_COMPETENCIAS', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='senttevaluationapp.perfil_competencias')),
                ('ID_SUB_GERENCIA', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='senttevaluationapp.sub_gerencia')),
            ],
        ),
        migrations.CreateModel(
            name='CUENTAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RUT', models.CharField(max_length=13)),
                ('CONTRASEÑA', models.CharField(max_length=80)),
                ('ID_PERFILES', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='senttevaluationapp.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='CUENTA_EVALUACION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ROL', models.CharField(max_length=30)),
                ('ID_CUENTA', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='senttevaluationapp.cuentas')),
                ('ID_EVALUACIONES', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='senttevaluationapp.evaluaciones')),
            ],
        ),
        migrations.AddField(
            model_name='competencia_asociada',
            name='ID_EVALUACIONES',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='senttevaluationapp.evaluaciones'),
        ),
        migrations.CreateModel(
            name='ACCIONES_CLAVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DESCRIPCIÓN', models.CharField(max_length=100)),
                ('PUNTUACIÓN', models.IntegerField()),
                ('ID_COMPETENCIA_ASOCIADA', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='senttevaluationapp.competencia_asociada')),
            ],
        ),
    ]
