# Generated by Django 3.2.7 on 2021-11-22 23:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senttevaluationapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planaccion',
            name='verificar',
            field=models.CharField(blank=True, choices=[(1, 'Si'), (2, 'No')], max_length=50, null=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]')]),
        ),
        migrations.AlterField(
            model_name='detalleev',
            name='AutoEvaluacion',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]')]),
        ),
        migrations.AlterField(
            model_name='detalleev',
            name='Calificacion',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]')]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='Rut',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(regex='\\b\\d{1,2}.\\d{3}.\\d{3}-[K|k|0-9]')]),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='AutoEvaluacion',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]')]),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='Calificacion',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]')]),
        ),
    ]
