# Generated by Django 3.2.7 on 2021-10-19 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senttevaluationapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accionclave',
            name='Descripcion',
            field=models.CharField(max_length=1000, unique=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]')]),
        ),
        migrations.AlterField(
            model_name='area',
            name='NombreArea',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]')]),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='NombreCompetencia',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]')]),
        ),
        migrations.AlterField(
            model_name='subgerencia',
            name='NombreSubgerencia',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]')]),
        ),
    ]
