# Generated by Django 3.2.7 on 2021-11-24 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senttevaluationapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='Calificacion',
        ),
        migrations.AddField(
            model_name='accionclave',
            name='Calificacion',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default=1, null=True, validators=[django.core.validators.RegexValidator(regex='^[0-7]')]),
        ),
    ]
