# Generated by Django 3.2.6 on 2021-09-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senttevaluationapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='FECHA_ANTIGUEDAD',
            field=models.CharField(max_length=50),
        ),
    ]
