# Generated by Django 3.2.6 on 2021-09-16 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('senttevaluationapp', '0002_alter_perfil_fecha_antiguedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='FECHA_INGRESO',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
