# Generated by Django 3.2.7 on 2021-11-24 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senttevaluationapp', '0002_auto_20211124_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accionclave',
            name='Calificacion',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.RegexValidator(regex='^[0-7]')]),
        ),
    ]
