# Generated by Django 3.2.7 on 2021-10-25 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senttevaluationapp', '0002_competencia_idperfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleadoeliminado',
            name='Rol',
        ),
    ]
