# Generated by Django 3.2.7 on 2021-10-21 20:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('senttevaluationapp', '0002_auto_20211019_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gerencia',
            name='IdArea',
        ),
        migrations.AddField(
            model_name='area',
            name='IdGerencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='senttevaluationapp.gerencia'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='Correo',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='Nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]')]),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='ComentarioCalibrador',
            field=models.CharField(max_length=80, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]')]),
        ),
        migrations.AlterField(
            model_name='perfilrol',
            name='NombreCalibrador',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfilrol',
            name='NombreEvaluador',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
