# Generated by Django 3.2.7 on 2021-11-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senttevaluationapp', '0002_remove_empleado_estadobarra'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='Imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
