# Generated by Django 3.2.7 on 2021-11-22 23:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senttevaluationapp', '0002_auto_20211122_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planaccion',
            name='verificar',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='verificar',
            field=models.CharField(blank=True, choices=[(1, 'Si'), (2, 'No')], max_length=50, null=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]')]),
        ),
    ]
