# Generated by Django 3.2.7 on 2021-10-25 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senttevaluationapp', '0003_remove_empleadoeliminado_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleadoeliminado',
            name='Contraseña',
        ),
    ]
