# Generated by Django 3.2.7 on 2021-10-23 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senttevaluationapp', '0003_auto_20211021_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencia',
            name='NombreCompetencia',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]')]),
        ),
    ]
