# Generated by Django 3.2.7 on 2021-10-04 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('senttevaluationapp', '0003_auto_20211003_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accionclave',
            name='IdCompetencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='senttevaluationapp.competencia'),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='IdPerfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='senttevaluationapp.perfil'),
        ),
        migrations.AlterField(
            model_name='detalleev',
            name='IdEvaluacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='senttevaluationapp.evaluacion'),
        ),
        migrations.AlterField(
            model_name='detalleev',
            name='IdPlanAccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='senttevaluationapp.planaccion'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='IdSubGerencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='senttevaluationapp.subgerencia'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='Rol',
            field=models.CharField(choices=[(1, 'admin'), (2, 'evaluador'), (3, 'calibrador'), (4, 'evaluado')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='IdEmpleado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='senttevaluationapp.empleado'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='IdPerfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='senttevaluationapp.perfil'),
        ),
        migrations.AlterField(
            model_name='gerencia',
            name='IdArea',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='senttevaluationapp.area'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='IdCargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='senttevaluationapp.cargo'),
        ),
        migrations.AlterField(
            model_name='perfilrol',
            name='IdEmpleado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='senttevaluationapp.empleado'),
        ),
        migrations.AlterField(
            model_name='subgerencia',
            name='IdGerencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='senttevaluationapp.gerencia'),
        ),
    ]
