# Generated by Django 3.2.7 on 2021-11-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senttevaluationapp', '0003_empleado_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='Imagen',
            field=models.ImageField(null=True, upload_to='usuarios'),
        ),
    ]
