# Generated by Django 3.2.7 on 2021-10-23 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senttevaluationapp', '0004_alter_competencia_nombrecompetencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accionclave',
            name='Descripcion',
            field=models.CharField(max_length=1000, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]')]),
        ),
    ]
