# Generated by Django 3.2.7 on 2021-10-05 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('senttevaluationapp', '0005_auto_20211004_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='Rol',
        ),
        migrations.RemoveField(
            model_name='perfilrol',
            name='IdEmpleado',
        ),
        migrations.AddField(
            model_name='empleado',
            name='IdRol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='senttevaluationapp.perfilrol'),
        ),
    ]
