# Generated by Django 3.2.7 on 2021-10-24 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('senttevaluationapp', '0005_alter_accionclave_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilComp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdCompetencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='senttevaluationapp.competencia')),
                ('IdPerfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='senttevaluationapp.perfil')),
            ],
        ),
    ]
