# Generated by Django 3.2.7 on 2021-11-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senttevaluationapp', '0006_alter_empleado_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='Imagen',
            field=models.ImageField(blank=True, default='foto_perfil.jpg', null=True, upload_to='usuarios'),
        ),
    ]
