# Generated by Django 3.2.7 on 2021-10-24 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senttevaluationapp', '0006_perfilcomp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competencia',
            name='IdPerfil',
        ),
    ]
