# Generated by Django 3.2.7 on 2021-10-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senttevaluationapp', '0006_auto_20211004_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilrol',
            name='Rol',
            field=models.IntegerField(choices=[(1, 'Evaluador'), (2, 'Evaluado'), (3, 'Calibrador')], default=1),
        ),
    ]
