# Generated by Django 3.2.7 on 2021-10-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senttevaluationapp', '0007_alter_perfilrol_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='FechaIngreso',
            field=models.DateField(auto_now=True),
        ),
    ]
