# Generated by Django 3.2.7 on 2021-11-15 15:08

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import senttevaluationapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('senttevaluationapp', '0007_alter_empleado_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleev',
            name='AutoEvaluacion',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]')]),
        ),
        migrations.AlterField(
            model_name='detalleev',
            name='Calificacion',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], null=True),
        ),
        migrations.AlterField(
            model_name='detalleev',
            name='ComentarioEvaluador',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]')]),
        ),
        migrations.AlterField(
            model_name='detalleev',
            name='FechaEvaluacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='ComentarioCalibrador',
            field=models.CharField(blank=True, max_length=80, null=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]')]),
        ),
        migrations.AlterField(
            model_name='perfilrol',
            name='NombreCalibrador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=senttevaluationapp.models.Empleado),
        ),
        migrations.AlterField(
            model_name='perfilrol',
            name='NombreEvaluador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=senttevaluationapp.models.Empleado),
        ),
    ]
