# Generated by Django 3.2.7 on 2021-10-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senttevaluationapp', '0008_empleado_fechaingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='FechaIngreso',
            field=models.DateField(),
        ),
    ]
