# Generated by Django 3.2.7 on 2021-10-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senttevaluationapp', '0008_empleado_fechaingreso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='Contraseña',
            new_name='Password',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='FechaIngreso',
            field=models.DateField(),
        ),
    ]
