# Generated by Django 3.2.7 on 2021-11-15 21:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senttevaluationapp', '0008_auto_20211115_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='Rut',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(regex='\\b\\d{1,2}.\\d{3}.\\d{3}-[K|k|0-9]')]),
        ),
    ]
